=== behrisch/selftest/carmen/matador/StaticRuleset/test_tmp/compile/MATADOR/recompile.dtd
<!ELEMENT PreviousCompilation (XMLLIB_IS_A_PIECE_OF_CRAP)+>
<!ATTLIST PreviousCompilation localityPoints CDATA #REQUIRED >
<!ELEMENT XMLLIB_IS_A_PIECE_OF_CRAP (ENTRY)+>
<!ELEMENT ENTRY EMPTY>
<!ATTLIST ENTRY name CDATA #REQUIRED indexType CDATA #REQUIRED index CDATA #REQUIRED >

=== behrisch/selftest/carmen/matador/PersonalRuleSet/test_tmp/compile/MATADOR/Matador_5_recompile.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE PreviousCompilation SYSTEM "recompile.dtd">
<PreviousCompilation localityPoints="94">
<XMLLIB_IS_A_PIECE_OF_CRAP>
<ENTRY index="0" indexType="_builtin.const" name="apc_cas_is_active"/>
<ENTRY index="2" indexType="_builtin.const" name="apc_cas_shift_improve_loop"/>
<ENTRY index="1" indexType="_builtin.const" name="apc_pac_is_active"/>
<ENTRY index="18" indexType="_builtin.const" name="connection_matrix_setup"/>
<ENTRY index="17" indexType="_builtin.const" name="is_generating"/>
<ENTRY index="5" indexType="_builtin.const" name="planning_crew_position_1"/>
<ENTRY index="14" indexType="_builtin.const" name="planning_crew_position_10"/>
<ENTRY index="15" indexType="_builtin.const" name="planning_crew_position_11"/>
<ENTRY index="16" indexType="_builtin.const" name="planning_crew_position_12"/>
<ENTRY index="6" indexType="_builtin.const" name="planning_crew_position_2"/>
<ENTRY index="7" indexType="_builtin.const" name="planning_crew_position_3"/>
<ENTRY index="8" indexType="_builtin.const" name="planning_crew_position_4"/>
<ENTRY index="9" indexType="_builtin.const" name="planning_crew_position_5"/>
<ENTRY index="10" indexType="_builtin.const" name="planning_crew_position_6"/>
<ENTRY index="11" indexType="_builtin.const" name="planning_crew_position_7"/>
<ENTRY index="12" indexType="_builtin.const" name="planning_crew_position_8"/>
<ENTRY index="13" indexType="_builtin.const" name="planning_crew_position_9"/>
<ENTRY index="4" indexType="_builtin.const" name="shift_improve_solution_number"/>
<ENTRY index="3" indexType="_builtin.const" name="shift_improve_sweep_number"/>
<ENTRY index="3" indexType="_topmodule.leg" name="activity_type"/>
<ENTRY index="63" indexType="_topmodule.leg" name="aircraft_change"/>
<ENTRY index="64" indexType="_topmodule.leg" name="aircraft_owner"/>
<ENTRY index="62" indexType="_topmodule.leg" name="aircraft_type"/>
<ENTRY index="81" indexType="_topmodule.leg" name="aircraft_type_custom"/>
<ENTRY index="1" indexType="_topmodule.leg" name="arrival"/>
<ENTRY index="57" indexType="_topmodule.leg" name="arrival_airport_base"/>
<ENTRY index="55" indexType="_topmodule.leg" name="arrival_airport_city"/>
<ENTRY index="10" indexType="_topmodule.leg" name="arrival_airport_country"/>
<ENTRY index="4" indexType="_topmodule.leg" name="arrival_airport_name"/>
<ENTRY index="11" indexType="_topmodule.leg" name="arrival_latitude"/>
<ENTRY index="13" indexType="_topmodule.leg" name="arrival_longitude"/>
<ENTRY index="59" indexType="_topmodule.leg" name="arrival_time_zone"/>
<ENTRY index="41" indexType="_topmodule.leg" name="assigned_crew_position_1"/>
<ENTRY index="50" indexType="_topmodule.leg" name="assigned_crew_position_10"/>
<ENTRY index="51" indexType="_topmodule.leg" name="assigned_crew_position_11"/>
<ENTRY index="52" indexType="_topmodule.leg" name="assigned_crew_position_12"/>
<ENTRY index="42" indexType="_topmodule.leg" name="assigned_crew_position_2"/>
<ENTRY index="43" indexType="_topmodule.leg" name="assigned_crew_position_3"/>
<ENTRY index="44" indexType="_topmodule.leg" name="assigned_crew_position_4"/>
<ENTRY index="45" indexType="_topmodule.leg" name="assigned_crew_position_5"/>
<ENTRY index="46" indexType="_topmodule.leg" name="assigned_crew_position_6"/>
<ENTRY index="47" indexType="_topmodule.leg" name="assigned_crew_position_7"/>
<ENTRY index="48" indexType="_topmodule.leg" name="assigned_crew_position_8"/>
<ENTRY index="49" indexType="_topmodule.leg" name="assigned_crew_position_9"/>
<ENTRY index="53" indexType="_topmodule.leg" name="assigned_function"/>
<ENTRY index="29" indexType="_topmodule.leg" name="booked_crew_position_1"/>
<ENTRY index="38" indexType="_topmodule.leg" name="booked_crew_position_10"/>
<ENTRY index="39" indexType="_topmodule.leg" name="booked_crew_position_11"/>
<ENTRY index="40" indexType="_topmodule.leg" name="booked_crew_position_12"/>
<ENTRY index="30" indexType="_topmodule.leg" name="booked_crew_position_2"/>
<ENTRY index="31" indexType="_topmodule.leg" name="booked_crew_position_3"/>
<ENTRY index="32" indexType="_topmodule.leg" name="booked_crew_position_4"/>
<ENTRY index="33" indexType="_topmodule.leg" name="booked_crew_position_5"/>
<ENTRY index="34" indexType="_topmodule.leg" name="booked_crew_position_6"/>
<ENTRY index="35" indexType="_topmodule.leg" name="booked_crew_position_7"/>
<ENTRY index="36" indexType="_topmodule.leg" name="booked_crew_position_8"/>
<ENTRY index="37" indexType="_topmodule.leg" name="booked_crew_position_9"/>
<ENTRY index="79" indexType="_topmodule.leg" name="changed_assignment"/>
<ENTRY index="82" indexType="_topmodule.leg" name="crr_has_base_variant"/>
<ENTRY index="77" indexType="_topmodule.leg" name="crr_name"/>
<ENTRY index="78" indexType="_topmodule.leg" name="crr_name_as_integer"/>
<ENTRY index="65" indexType="_topmodule.leg" name="deadhead"/>
<ENTRY index="2" indexType="_topmodule.leg" name="departure"/>
<ENTRY index="56" indexType="_topmodule.leg" name="departure_airport_base"/>
<ENTRY index="54" indexType="_topmodule.leg" name="departure_airport_city"/>
<ENTRY index="9" indexType="_topmodule.leg" name="departure_airport_country"/>
<ENTRY index="8" indexType="_topmodule.leg" name="departure_airport_name"/>
<ENTRY index="12" indexType="_topmodule.leg" name="departure_latitude"/>
<ENTRY index="14" indexType="_topmodule.leg" name="departure_longitude"/>
<ENTRY index="58" indexType="_topmodule.leg" name="departure_time_zone"/>
<ENTRY index="16" indexType="_topmodule.leg" name="environment_activity"/>
<ENTRY index="71" indexType="_topmodule.leg" name="flight_carrier"/>
<ENTRY index="18" indexType="_topmodule.leg" name="flight_duty"/>
<ENTRY index="0" indexType="_topmodule.leg" name="flight_number"/>
<ENTRY index="7" indexType="_topmodule.leg" name="flight_suffix"/>
<ENTRY index="72" indexType="_topmodule.leg" name="ground_activity"/>
<ENTRY index="19" indexType="_topmodule.leg" name="ground_duty"/>
<ENTRY index="20" indexType="_topmodule.leg" name="ground_duty_code"/>
<ENTRY index="22" indexType="_topmodule.leg" name="ground_duty_code_suffix"/>
<ENTRY index="21" indexType="_topmodule.leg" name="ground_duty_main_code"/>
<ENTRY index="66" indexType="_topmodule.leg" name="ground_duty_sub_code"/>
<ENTRY index="74" indexType="_topmodule.leg" name="ground_transport"/>
<ENTRY index="26" indexType="_topmodule.leg" name="homebase_arrival"/>
<ENTRY index="28" indexType="_topmodule.leg" name="homebase_arrival_summer"/>
<ENTRY index="25" indexType="_topmodule.leg" name="homebase_departure"/>
<ENTRY index="27" indexType="_topmodule.leg" name="homebase_departure_summer"/>
<ENTRY index="23" indexType="_topmodule.leg" name="leg_number"/>
<ENTRY index="61" indexType="_topmodule.leg" name="local_arrival_time"/>
<ENTRY index="5" indexType="_topmodule.leg" name="local_arrival_time_summer"/>
<ENTRY index="60" indexType="_topmodule.leg" name="local_departure_time"/>
<ENTRY index="6" indexType="_topmodule.leg" name="local_departure_time_summer"/>
<ENTRY index="83" indexType="_topmodule.leg" name="locked_activity"/>
<ENTRY index="75" indexType="_topmodule.leg" name="oag"/>
<ENTRY index="67" indexType="_topmodule.leg" name="off_duty"/>
<ENTRY index="68" indexType="_topmodule.leg" name="off_duty_code"/>
<ENTRY index="69" indexType="_topmodule.leg" name="off_duty_sub_code"/>
<ENTRY index="80" indexType="_topmodule.leg" name="onward_ref_flight_number"/>
<ENTRY index="70" indexType="_topmodule.leg" name="passenger_terminal_departure_station"/>
<ENTRY index="73" indexType="_topmodule.leg" name="personal_activity"/>
<ENTRY index="15" indexType="_topmodule.leg" name="preassigned_activity"/>
<ENTRY index="76" indexType="_topmodule.leg" name="service_type"/>
<ENTRY index="24" indexType="_topmodule.leg" name="trip_homebase"/>
<ENTRY index="17" indexType="_topmodule.leg" name="trip_id"/>
<ENTRY index="84" indexType="_topmodule.leg" name="turnout_leg_arrival"/>
<ENTRY index="85" indexType="_topmodule.leg" name="turnout_leg_departure"/>
<ENTRY index="86" indexType="_topmodule.leg" name="user_tag_0"/>
<ENTRY index="87" indexType="_topmodule.leg" name="user_tag_1"/>
<ENTRY index="88" indexType="_topmodule.leg" name="user_tag_2"/>
<ENTRY index="89" indexType="_topmodule.leg" name="user_tag_3"/>
<ENTRY index="90" indexType="_topmodule.leg" name="user_tag_4"/>
<ENTRY index="91" indexType="_topmodule.leg" name="user_tag_5"/>
<ENTRY index="92" indexType="_topmodule.leg" name="user_tag_6"/>
<ENTRY index="93" indexType="_topmodule.leg" name="user_tag_7"/>
<ENTRY index="94" indexType="_topmodule.leg" name="user_tag_8"/>
<ENTRY index="95" indexType="_topmodule.leg" name="user_tag_9"/>
<ENTRY index="9" indexType="_topmodule.roster" name="_topmodule.%block_time_roster%"/>
<ENTRY index="0" indexType="_topmodule.roster" name="crr_crew_id"/>
<ENTRY index="6" indexType="_topmodule.roster" name="crr_is_closed_last"/>
<ENTRY index="1" indexType="_topmodule.roster" name="homebase"/>
<ENTRY index="5" indexType="_topmodule.roster" name="homebase_country"/>
<ENTRY index="8" indexType="_topmodule.roster" name="lp_period_end"/>
<ENTRY index="7" indexType="_topmodule.roster" name="lp_period_start"/>
<ENTRY index="2" indexType="_topmodule.roster" name="nothing_scheduled"/>
<ENTRY index="4" indexType="_topmodule.roster" name="shift_improve_tw_end"/>
<ENTRY index="3" indexType="_topmodule.roster" name="shift_improve_tw_start"/>
<ENTRY index="0" indexType="_topmodule.trip" name="_topmodule.%connection_time%"/>
<ENTRY index="0" indexType="fileNumber" name="_topmodule.%active_function%"/>
<ENTRY index="0" indexType="fileNumber" name="_topmodule.%ah_pos%"/>
<ENTRY index="0" indexType="fileNumber" name="_topmodule.%ai_pos%"/>
<ENTRY index="0" indexType="fileNumber" name="_topmodule.%ap_pos%"/>
<ENTRY index="0" indexType="fileNumber" name="_topmodule.%block_time_environment%"/>
<ENTRY index="0" indexType="fileNumber" name="_topmodule.%block_time_leg%"/>
<ENTRY index="0" indexType="fileNumber" name="_topmodule.%block_time_roster%"/>
